#!/usr/bin/env bash
#
# One-time Cloudflare Tunnel setup.
#
# Installs cloudflared (Mac), logs you into Cloudflare, creates a named tunnel,
# routes your custom hostname to it, and writes a project-local config so
# start.sh knows how to run it.
#
# Re-runnable: safe to run again if you change the hostname or rename the tunnel.
#
set -euo pipefail
cd "$(dirname "$0")"

# ── 1. Install cloudflared if missing ─────────────────────────
if ! command -v cloudflared >/dev/null 2>&1; then
    OS=$(uname -s)
    case "$OS" in
        Darwin)
            if command -v brew >/dev/null 2>&1; then
                echo "▶ Installing cloudflared via Homebrew..."
                brew install cloudflared
            else
                echo "❌ Homebrew not found. Install it from https://brew.sh, then re-run."
                exit 1
            fi
            ;;
        Linux)
            echo "❌ On Linux, install cloudflared manually from:"
            echo "   https://github.com/cloudflare/cloudflared/releases"
            echo "   For Raspberry Pi: download the linux-arm64 .deb and run 'sudo dpkg -i <file>'."
            exit 1
            ;;
        *)
            echo "❌ Unsupported OS: $OS"
            exit 1
            ;;
    esac
fi
echo "✓ cloudflared: $(cloudflared --version 2>&1 | head -1)"

# ── 2. Browser login (only if no cert yet) ────────────────────
CERT="$HOME/.cloudflared/cert.pem"
if [[ ! -f "$CERT" ]]; then
    echo ""
    echo "▶ A browser window will open. Pick the domain you want to use, then return here."
    echo "  (If no window opens, follow the URL cloudflared prints.)"
    cloudflared tunnel login
fi
echo "✓ Authenticated."

# ── 3. Collect inputs ─────────────────────────────────────────
echo ""
read -rp "Tunnel name [finance-tracker]: " TUNNEL_NAME
TUNNEL_NAME="${TUNNEL_NAME:-finance-tracker}"

read -rp "Public hostname (e.g. finance.yourdomain.com): " HOSTNAME
if [[ -z "$HOSTNAME" ]]; then
    echo "❌ Hostname is required."
    exit 1
fi

# ── 4. Create tunnel (idempotent) ─────────────────────────────
if cloudflared tunnel create "$TUNNEL_NAME" 2>/dev/null; then
    echo "✓ Created tunnel '$TUNNEL_NAME'."
else
    echo "✓ Tunnel '$TUNNEL_NAME' already exists — reusing it."
fi

# Resolve the tunnel ID (skip the header line)
TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null \
    | awk -v n="$TUNNEL_NAME" 'NR>1 && $2==n {print $1; exit}')
if [[ -z "$TUNNEL_ID" ]]; then
    echo "❌ Could not resolve tunnel ID for '$TUNNEL_NAME'."
    exit 1
fi
CRED_FILE="$HOME/.cloudflared/${TUNNEL_ID}.json"
if [[ ! -f "$CRED_FILE" ]]; then
    echo "❌ Credentials file missing at $CRED_FILE"
    echo "   Try deleting the tunnel and re-running: cloudflared tunnel delete $TUNNEL_NAME"
    exit 1
fi

# ── 5. Route DNS ──────────────────────────────────────────────
echo ""
echo "▶ Routing $HOSTNAME → tunnel $TUNNEL_NAME..."
cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" \
    || echo "  (route may already exist — continuing)"

# ── 6. Write project-local config ─────────────────────────────
mkdir -p cloudflared
cat > cloudflared/config.yml <<EOF
# Auto-generated by setup-tunnel.sh — re-run that script to change hostname/tunnel.
tunnel: $TUNNEL_NAME
credentials-file: $CRED_FILE

ingress:
  - hostname: $HOSTNAME
    service: http://localhost:8000
  - service: http_status:404
EOF

echo ""
echo "✓ Wrote cloudflared/config.yml"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Setup complete. Next:"
echo ""
echo "   1) Make sure .env is filled in     (cp .env.example .env)"
echo "   2) Start everything:               ./start.sh"
echo "   3) Open in your browser:           https://$HOSTNAME"
echo ""
echo "  Recommended Cloudflare dashboard settings:"
echo "   • SSL/TLS → Full (strict)"
echo "   • SSL/TLS → Edge Certificates → Always Use HTTPS: on"
echo "   • Security → Bot Fight Mode: on"
echo "   • Zero Trust → Access → put an email-OTP rule in front of $HOSTNAME"
echo "═══════════════════════════════════════════════════════════"
